### PR TITLE
Fix #161: MeiliSearch::Index times out

### LINKED ISSUE #161: MeiliSearch::Index times out
MeiliSearch::Index times out when indexing a lot of data. The default timeout is 1.

The following page states that the timeout can be increased:
https://github.com/meilisearch/meilisearch-ruby/wiki/Client-Options

However, the MeiliSearch::Client does not pass the options to MeiliSearch::Index, so the default timeout and max_retries is always used:

https://github.com/meilisearch/meilisearch-ruby/blob/8d2251d51f5d4ea8b54db337071dd32d8d2f9b11/lib/meilisearch/client.rb#L90-L92

https://github.com/meilisearch/meilisearch-ruby/blob/8d2251d51f5d4ea8b54db337071dd32d8d2f9b11/lib/meilisearch/index.rb#L10-L14

### PR DESCRIPTION
**Pull request by christianhellsten**
Pass options from MeiliSearch::Client to MeiliSearch::Index

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Just FYI, we encourage everyone to make a PR from a **new branch** created in their fork-repository instead of doing it from their own `main`, it is a good practice! For example, if your PR was not merged you would have had a broken `main` branch compared to ours.
See here our [contribution guidelines](https://github.com/meilisearch/meilisearch-js/blob/main/CONTRIBUTING.md#how-to-contribute).
I'm saying this for the next time, let's keep it like this for this PR. 😉

**Comment by bidoubiwa** [comment]
Hello @christianhellsten 
Thanks a lot for this PR! It is a great great addition :) So sorry for the delay. 
 
I have tested it and the timeout option works! I'm not sure about the `max_retries` as I could not confirm the retries occurred. 

About the timeout. Is it possible to add the following test in `documents_spec.rb`
```ruby
    it 'add documents on zero timeout client option' do
      zero_timeout_client = MeiliSearch::Client.new($URL, $MASTER_KEY, @options = { timeout: 0, max_retries: 1 })
      new_index = @zero_timeout_client.index('newIndex')
      expect do
        new_index.add_documents(documents)
      end.to raise_error(Timeout::Error)
    end
```

I was wondering if we could test `max_retries` ? If you have any idea that's cool, if no, no problem I will write an issue about it!

**Review by bidoubiwa — CHANGES_REQUESTED** [review]
See above

**Comment by christianhellsten** [comment]
Thank you @bidoubiwa. I added the test you suggested and one for max_retries:

    it 'supports max_retries option' do
      max_retries_client = MeiliSearch::Client.new($URL, $MASTER_KEY, @options = { max_retries: 2 })
      http = Net::HTTP.new('localhost', 7700)
      new_index = max_retries_client.index('newIndex')
      expect(Net::HTTP).to receive(:new).with('localhost', 7700).and_return(http)
      expect(http).to receive(:max_retries=).with(2)
      new_index.add_documents(documents)
    end

If you want TCP-level integration tests then, for example, toxiproxy could be a solution for adding jitter and/or latency:
https://github.com/Shopify/toxiproxy/

Sorry about the missing branch. I didn't plan to create a PR when I created the fork.

**Comment by bidoubiwa** [comment]
Hey @christianhellsten, thanks for getting back and apply those changes 🔥

> If you want TCP-level integration tests then, for example, toxiproxy could be a solution for adding jitter and/or latency:
https://github.com/Shopify/toxiproxy/

I'll create an issue about it but lets continue without. 

Tests had to be approved (new thing) and I see your linter checked failed! Could you fix that and then we can merge?

**Comment by christianhellsten** [comment]
Weird, .rubocop_todo.yml allows 465 lines:

```yaml
 12 Metrics/BlockLength:
 13   Max: 465
```

I think it might be best to ignore block length in tests:

```yaml
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
```

I can add this to .rubocop.yml if you think it's an acceptable solution.

**Comment by curquiza** [comment]
> I think it might be best to ignore block length in tests:
> 
> ```yaml
> Metrics/BlockLength:
>   IgnoredMethods: ['describe', 'context']
> ```
> 
> I can add this to .rubocop.yml if you think it's an acceptable solution.

Oh I did not know it was possible to do this! It seems like a good solution 🙂

**Comment by christianhellsten** [comment]
I haven't had time to look into why the linter is failing. The linter reports no errors on my machine and there are only 392 lines vs. 432 allowed.

I can create a separate PR to try to fix the linter error:

> spec/meilisearch/index/documents_spec.rb:3:1: C: Metrics/BlockLength: Block has too many lines. [452/432]

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
(bors has issues at the moment)

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
GitHub seems to be buggy because you did your PR from your `main` to our `main` (instead of creating a new branch). Your `.rubocop_todo.yml` file was updated 11 months ago and GitHub does not take it into account in your PR, see our `.rubocop_todo.yml` in main: the max is 445. And the 465 in your `.rubucop_todo.yml` is not present in your PR.
Can you try to change your `.rubocop_todo.yml` file with another value (like 466) please?

**Comment by curquiza** [comment]
Replaced by #188. I added you @christianhellsten in the commit authors so you will be in the contributor list :)

**Pull request closed without merging**
