### PR TITLE
Add synchronous bang methods

### PR DESCRIPTION
**Pull request by CaroFG**

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Thanks for your PR! ❤️ 
Could you add:
- `delete_documents!`
- `update_documents!`
- and tests 😇

**Review by curquiza — APPROVED** [review]
LGTM! Thanks @CaroFG!
Waiting for the @bidoubiwa approval before merging it

**Comment by bidoubiwa** [comment]
Since the synchrone method could potentially take a very long time to come back on big datasets, should we pass the timeout  and interval parameters that is available on `wait_for_pending_update` ? 

```
 def wait_for_pending_update(update_id, timeout_in_ms = 5000, interval_in_ms = 50)
  ```

``` ruby  
   def add_documents!(documents, primary_key = nil, timeout_in_ms = 5000, interval_in_ms = 50)
```

Since he does not access wait_for_pending_update directly, it's also a loss in configuration

**Comment by curquiza** [comment]
Hum I would rather not complexify these methods for the moment. These methods are for tests purpose only and should not be used in production. I will add them to the wiki with this warning, but we can also add a comment above each method in the code `# for test purposes only, should not be used in production`.
@CaroFG needs these methods for the rails integration and they are used in methods that already have this warning `do not use in production`

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Comment by bidoubiwa** [comment]
@curquiza if this is for not-production but for testing, users may want to test on a bigger dataset or just on a MeiliSearch that is on a small server and adding complexity on a function that is not supposed to be used by the end user is maybe not that bad! 

But if you bot think it is overkill, no problem for me!

**Comment by curquiza** [comment]
(Sorry I removed my comment by mistake, so sorry)

**Comment by curquiza** [comment]
I can understand this might be useful even for test purposes. But this is not a method someone needs in production so it seems a little bit overkill for a first addition to add that much configuration.

But we definitely know how to add it (and accept PRs with tests) if someone needs it 🙂
I don't want to add works on Caro's plate for the moment.
This is nice to you @CaroFG to have added these methods with a lot of tests! 🎉

**Review by curquiza — APPROVED** [review]
Let's merge then! 🚀 

bors merge

**Pull request merged**
