### PR TITLE
Replace movies with book in README

### PR DESCRIPTION
**Pull request by bidoubiwa**

### CODE REVIEW

**Review by CaroFG — DISMISSED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
Not sure what is happening here: @curquiza

**Comment by eskombro** [comment]
I think #154 should fix the problem 🤞🏽

**Comment by curquiza** [comment]
The fail is not related to your PR @eskombro but to this issue #60 
However, this is a nice fix you did 😄

**Comment by curquiza** [comment]
https://github.com/meilisearch/meilisearch-ruby/pull/153 seems to have fixed the same issue as this PR, right?

**Comment by bidoubiwa** [comment]
Rebase had a weird behavior. Recreating.

**Pull request closed without merging**
