### PR TITLE
add timeout hint to README

### PR DESCRIPTION
**Pull request by gurgeous**
See https://github.com/meilisearch/MeiliSearch/issues/1200

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @gurgeous! Thanks for your PR! There was indeed a documentation issue here! 😄 

We don't want to make the README too complex, that's why we don't put too much configuration on it. However this is an important point to document, so I've just created a [Wiki](https://github.com/meilisearch/meilisearch-ruby/wiki) for this repo. And here is the related section to the point you mention: https://github.com/meilisearch/meilisearch-ruby/wiki/Client-Options
Tell me if this guide is enough for you 🙂

I suggest we add a link to this section in the README, to make it visible for users.
For example, below the line "With the updateId, you can check the status..." (after the document addition in the getting started) we could add:
```
💡 To customize the `Client`, for example, increasing the default timeout, please check out [this section](https://github.com/meilisearch/meilisearch-ruby/wiki/Client-Options).
```

WDYT?
If you don't have time to update this PR, I can create another one of course 😊 I just wanted to let you the opportunity to be officially one of our contributors since you are really involved in the product 😇

**Comment by gurgeous** [comment]
Sure, let me take a look

**Comment by gurgeous** [comment]
How about this? :)

**Review by curquiza — APPROVED** [review]
Awesome, thanks again for your involvement!!

bors merge

**Pull request merged**
