### PR TITLE
Create Dockerfile and build install to it

### PR DESCRIPTION
**Pull request by thicolares**
# Pull Request

## Related issue
- No issue related.

## What does this PR do?
- Create Dockerfile and `build install` to it.
- So we don't need to run this every time we create a new Docker image.
- Improve Dockerfile we use for development :)

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by brunoocasali** [comment]
Hi @thicolares can you give me more info about this statement?

> So we don't need to run this every time we create a new Docker image.

The `bundle install` command is only needed once, and all of its results will be saved in the volume `bundle`. We just added it to `CONTRIBUTING.md` because is a good practice to make it clear to the contributor what it needs to do to run the project quickly.

**Comment by thicolares** [comment]
> The `bundle install` command is only needed once, and all of its results will be saved in the volume `bundle`. We just added it to `CONTRIBUTING.md` because is a good practice to make it clear to the contributor what it needs to do to run the project quickly.

Thanks for this feedback, @brunoocasali! 

My intention is also to make it easier for the contributor. And with this change, this would be even quicker. Because now we'll have all gems installed once during the image creation -- i.e. during the first call. Every subsequent Docker command using this image will be even faster :) And no extra knowledge on the part of the user is required.

But if one decided to add new dependencies -- i.e. advance contribution; I documented how to explicitly build the image again.

**Comment by brunoocasali** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Comment by brunoocasali** [comment]
As discussed in the Slack community chat, this new version didn't work correctly in all docker environments. I'll close the PR. Feel free to reopen it if needed!

**Pull request closed without merging**
