### PR TITLE
Add method to use faceting sub routes

### PR DESCRIPTION
**Pull request by curquiza**
NB: tests do not run yet because the v0.11 is not out.
If you want to run the tests with the last version of MeiliSearch, use `cargo` in the MeiliSearch repo, and go on my branch.

### CODE REVIEW

**Comment by eskombro** [comment]
I test your PR and get 7 failing tests.

My testing steps:

For `MeiliSearch`

1. Pull origin master du repo `meilisearch`
2. cargo build --release
3. ./target/release/meilisearch --master-key=masterKey

For `meilisearch-ruby`

1. git pull origin master
2. git checkout add-facets-settings-routes
3. bundle exec rspec

```
Failures:

  1) MeiliSearch::Index - Documents All basic tests with primary-key inference browses documents with query parameters
     Failure/Error: expect(response.first['objectId']).to eq(1)
     
       expected: 1
            got: 123
     
       (compared using ==)
     # ./spec/meilisearch/index/documents_spec.rb:69:in `block (3 levels) in <top (required)>'

  2) MeiliSearch::Index - Settings On global settings routes gets default values of settings
     Failure/Error: expect(response.keys).to contain_exactly(*settings_keys)
     
       expected collection contained:  ["acceptNewFields", "attributesForFaceting", "displayedAttributes", "distinctAttribute", "rankingRules", "searchableAttributes", "stopWords", "synonyms"]
       actual collection contained:    ["acceptNewFields", "displayedAttributes", "distinctAttribute", "rankingRules", "searchableAttributes", "stopWords", "synonyms"]
       the missing elements were:      ["attributesForFaceting"]
     # ./spec/meilisearch/index/settings_spec.rb:46:in `block (3 levels) in <top (required)>'

  3) MeiliSearch::Index - Settings On attributes-for-faceting sub-routes gets default values of attributes for faceting
     Failure/Error: raise HTTPError.new(response.code, response.message, response.body) unless response.success?
     
     MeiliSearch::HTTPError:
       Not found
     # ./lib/meilisearch/http_request.rb:69:in `validate'
     # ./lib/meilisearch/http_request.rb:26:in `http_get'
     # ./lib/meilisearch/index.rb:238:in `attributes_for_faceting'
     # ./spec/meilisearch/index/settings_spec.rb:411:in `block (3 levels) in <top (required)>'

  4) MeiliSearch::Index - Settings On attributes-for-faceting sub-routes updates attributes for faceting
     Failure/Error: raise HTTPError.new(response.code, response.message, response.body) unless response.success?
     
     MeiliSearch::HTTPError:
       Not found
     # ./lib/meilisearch/http_request.rb:69:in `validate'
     # ./lib/meilisearch/http_request.rb:40:in `http_post'
     # ./lib/meilisearch/index.rb:243:in `update_attributes_for_faceting'
     # ./spec/meilisearch/index/settings_spec.rb:417:in `block (3 levels) in <top (required)>'

  5) MeiliSearch::Index - Settings On attributes-for-faceting sub-routes resets attributes for faceting
     Failure/Error: raise HTTPError.new(response.code, response.message, response.body) unless response.success?
     
     MeiliSearch::HTTPError:
       Not found
     # ./lib/meilisearch/http_request.rb:69:in `validate'
     # ./lib/meilisearch/http_request.rb:63:in `http_delete'
     # ./lib/meilisearch/index.rb:247:in `reset_attributes_for_faceting'
     # ./spec/meilisearch/index/settings_spec.rb:424:in `block (3 levels) in <top (required)>'

  6) MeiliSearch::Index - Settings Index with primary-key gets the default values of settings
     Failure/Error: expect(response.keys).to contain_exactly(*settings_keys)
     
       expected collection contained:  ["acceptNewFields", "attributesForFaceting", "displayedAttributes", "distinctAttribute", "rankingRules", "searchableAttributes", "stopWords", "synonyms"]
       actual collection contained:    ["acceptNewFields", "displayedAttributes", "distinctAttribute", "rankingRules", "searchableAttributes", "stopWords", "synonyms"]
       the missing elements were:      ["attributesForFaceting"]
     # ./spec/meilisearch/index/settings_spec.rb:445:in `block (3 levels) in <top (required)>'

  7) MeiliSearch::Index - Stats gets the distribution of fields
     Failure/Error: expect(response).to be_a(Hash)
       expected nil to be a kind of Hash
     # ./spec/meilisearch/index/stats_spec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 8.91 seconds (files took 0.42274 seconds to load)
115 examples, 7 failures

Failed examples:

rspec ./spec/meilisearch/index/documents_spec.rb:65 # MeiliSearch::Index - Documents All basic tests with primary-key inference browses documents with query parameters
rspec ./spec/meilisearch/index/settings_spec.rb:43 # MeiliSearch::Index - Settings On global settings routes gets default values of settings
rspec ./spec/meilisearch/index/settings_spec.rb:410 # MeiliSearch::Index - Settings On attributes-for-faceting sub-routes gets default values of attributes for faceting
rspec ./spec/meilisearch/index/settings_spec.rb:416 # MeiliSearch::Index - Settings On attributes-for-faceting sub-routes updates attributes for faceting
rspec ./spec/meilisearch/index/settings_spec.rb:423 # MeiliSearch::Index - Settings On attributes-for-faceting sub-routes resets attributes for faceting
rspec ./spec/meilisearch/index/settings_spec.rb:442 # MeiliSearch::Index - Settings Index with primary-key gets the default values of settings
rspec ./spec/meilisearch/index/stats_spec.rb:35 # MeiliSearch::Index - Stats gets the distribution of fields

Coverage report generated for RSpec to /Users/esk/Meili/meilisearch-ruby/coverage. 869 / 892 LOC (97.42%) covered.
SimpleCov failed with exit 1
```

**Comment by curquiza** [comment]
@eskombro `git fetch origin`?

**Comment by eskombro** [comment]
> @eskombro `git fetch origin`?

Nothing, same :/

**Comment by eskombro** [comment]
Ok, get 3 Failures:

```
Failures:

  1) MeiliSearch::Client - Keys fails to get settings if public key used
     Failure/Error: expect { new_client.index(@uid).settings }.to raise_meilisearch_http_error_with(403)
     
       expected Exception with an instance of MeiliSearch::HTTPError and having attributes {:code => 403}, got #<MeiliSearch::HTTPError: 401: Unauthorized - Invalid api key: 3b3bf839485f90453acc6159ba18fbed673ca88523093def11a9b4f4320e44a5.> with backtrace:
         # ./lib/meilisearch/http_request.rb:69:in `validate'
         # ./lib/meilisearch/http_request.rb:26:in `http_get'
         # ./lib/meilisearch/index.rb:121:in `settings'
         # ./spec/meilisearch/client/keys_spec.rb:24:in `block (3 levels) in <top (required)>'
         # ./spec/meilisearch/client/keys_spec.rb:24:in `block (2 levels) in <top (required)>'
     # ./spec/meilisearch/client/keys_spec.rb:24:in `block (2 levels) in <top (required)>'

  2) MeiliSearch::Client - Keys fails to get keys if private key used
     Failure/Error: expect { new_client.keys }.to raise_meilisearch_http_error_with(403)
     
       expected Exception with an instance of MeiliSearch::HTTPError and having attributes {:code => 403}, got #<MeiliSearch::HTTPError: 401: Unauthorized - Invalid api key: 8dcbb482663333d0280fa9fedf0e0c16d52185cb67db494ce4cd34da32ce2092.> with backtrace:
         # ./lib/meilisearch/http_request.rb:69:in `validate'
         # ./lib/meilisearch/http_request.rb:26:in `http_get'
         # ./lib/meilisearch/client.rb:49:in `keys'
         # ./spec/meilisearch/client/keys_spec.rb:30:in `block (3 levels) in <top (required)>'
         # ./spec/meilisearch/client/keys_spec.rb:30:in `block (2 levels) in <top (required)>'
     # ./spec/meilisearch/client/keys_spec.rb:30:in `block (2 levels) in <top (required)>'

  3) MeiliSearch::Index fails to manipulate index object after deletion
     Failure/Error: expect { @index2.delete }.to raise_meilisearch_http_error_with(404)
       expected Exception with an instance of MeiliSearch::HTTPError and having attributes {:code => 404} but nothing was raised
     # ./spec/meilisearch/index/base_spec.rb:61:in `block (2 levels) in <top (required)>'

Finished in 8.01 seconds (files took 0.39283 seconds to load)
115 examples, 3 failures

Failed examples:

rspec ./spec/meilisearch/client/keys_spec.rb:21 # MeiliSearch::Client - Keys fails to get settings if public key used
rspec ./spec/meilisearch/client/keys_spec.rb:27 # MeiliSearch::Client - Keys fails to get keys if private key used
rspec ./spec/meilisearch/index/base_spec.rb:57 # MeiliSearch::Index fails to manipulate index object after deletion

Coverage report generated for RSpec to /Users/esk/Meili/meilisearch-ruby/coverage. 892 / 892 LOC (100.0%) covered.
SimpleCov failed with exit 1
```

As you said, those arre waiting for fixes from MeiliSearch. Your code and tests look good to me tho 🎉

**Comment by eskombro** [comment]
I put those updates here to keep track:

https://github.com/meilisearch/MeiliSearch/issues/742
https://github.com/meilisearch/MeiliSearch/issues/741

@curquiza correct me if I'm wrong please :)

**Pull request merged**
